# Generated by Django 3.2.6 on 2025-10-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(help_text='URL path of the page', max_length=255, unique=True)),
                ('count', models.IntegerField(default=0, help_text='Number of visits to this page')),
                ('last_visited', models.DateTimeField(auto_now=True, help_text='Last visit timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='First visit timestamp')),
            ],
            options={
                'verbose_name': 'Visit Count',
                'verbose_name_plural': 'Visit Counts',
                'ordering': ['-count'],
            },
        ),
    ]
