# Generated by Django 3.2.6 on 2025-10-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(db_index=True, help_text='URL path of the page', max_length=255)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Visit timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Visitor IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
            ],
            options={
                'verbose_name': 'Visit Record',
                'verbose_name_plural': 'Visit Records',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitrecord',
            index=models.Index(fields=['page_url', 'visited_at'], name='ps_data_vis_page_ur_5ea591_idx'),
        ),
    ]
